greenchilly/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from web.urls import urlpatterns as  weburl

urlpatterns = [
    url(r'', include(weburl, 'web')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^login/$','django.contrib.auth.views.login'),
    url(r'^logout/$','django.contrib.auth.views.logout'),
    url(r'^passwordreset/$','django.contrib.auth.views.password_reset'),
    url(r'^passwordreset/done/$','django.contrib.auth.views.password_reset_done'),
    url(r'^admin/', admin.site.urls),
]

web/urls.py
from django.conf.urls import *

urlpatterns = patterns('web.views',
    (r'^$', 'index'),
    (r'^home/$', 'index'),
    (r'^statscsv/$', 'statscsv'),
    (r'^chart/(?P<ply>\d+)/$', 'chart'),
    (r'^holediff/$', 'holediff'),
    (r'^showmembergroupcards/$', 'showmembergroupcards'),
    (r'^holediffdate/$', 'holediffdate'),
    (r'^holediffdaterange/$', 'holediffdaterange'),
    (r'^roundstats/$', 'roundstats'),
    (r'^monthroundstats/(?P<year>\d+)/(?P<month>\d+)/$', 'monthroundstats'),
    (r'^holediffrange/(?P<mx>\d+)/(?P<mn>\d+)/$', 'holediffrange'),
    (r'^sorry/$', 'sorry'),
    (r'^calculatehandicap/$', 'calculatehandicap'),
    (r'^revisehandicap/$', 'revisehandicap'),
    (r'^displayhandicap/$', 'displayhandicap'),
    (r'^displayhandicaplist/$', 'getcurhandicaplist'),
    (r'^addcourse/((?P<id>\d+)/)?$', 'addcourse'),
    (r'^holestats/(?P<hle>\d+)/$', 'holestats'),
    (r'^holediffind/(?P<id>\d+)/$', 'holediffind'),
    (r'^addmember/$', 'addmember'),
    (r'^deletemember/(?P<id>\d+)/$', 'deletemember'),
    (r'^closetournament/((?P<trn>\d+)/)?$', 'closetournament'),
    (r'^matchplay/(?P<tournid>\d+)/$', 'matchplay'),
    (r'^tournamentfull/((?P<trn>\d+)/)?$', 'tournamentfull'),
    (r'^showdraw/(?P<drw>\d+)/$', 'showdraw'),
    (r'^adjustdraw/(?P<drw>\d+)/$', 'adjustdraw'),
    (r'^calculatehandicap/(?P<mem>\d+)/$', 'calculatehandicap'),
    (r'^finaldraw/(?P<drw>\d+)/$', 'finaldraw'),
    (r'^addtee/(?P<courseid>\d+)/((?P<id>\d+)/)?$', 'addtee'),
    (r'^adddraw/(?P<tourn>\d+)/$', 'adddraw'),
    (r'^leaderboard/(?P<trn>\d+)/(?P<nextt>\d+)/$', 'leaderboard'),
    (r'^multileaderboard/(?P<trp>\d+)/$', 'multileaderboard'),
    (r'^statistics/((?P<trn>\d+)/)?$', 'statistics'),
    (r'^addteeoff/(?P<drw>\d+)/((?P<id>\d+)/)?$', 'addteeoff'),
    (r'^addhole/(?P<teeid>\d+)/((?P<id>\d+)/)?$', 'addhole'),
    (r'^holestatsind/(?P<ply>\d+)/$', 'holestatsind'),
    (r'^managecourses/$', 'managecourses'),
    (r'^displaystats/$', 'displaystats'),
    (r'^manageleaderboards/$', 'manageleaderboards'),
    (r'^manageplayers/$', 'manageplayers'),
    (r'^displaytournaments/$', 'displaytournaments'),
    (r'^addplayer/((?P<id>\d+)/)?$', 'addplayer'),
    (r'^managehandicaps/$', 'managehandicaps'),
    (r'^addhandicap/(?P<plr>\d+)/((?P<id>\d+)/)?$', 'addhandicap'),
    (r'^addscores/((?P<matchentry>\d+)/)?$', 'addscores'),
    (r'^addrscores/(?P<rnd>\d+)/((?P<matchentry>\d+)/)?$', 'addrscores'),
    (r'^addpscores/((?P<prnd>\d+)/)?$', 'addpscores'),
    (r'^managetournaments/$', 'managetournaments'),
    (r'^managemembers/$', 'managemembers'),
    (r'^managepracticerounds/$', 'managepracticerounds'),
    (r'^addtournament/((?P<id>\d+)/)?$', 'addtournament'),
    (r'^deleteteam/(?P<id>\d+)/$', 'deleteteam'),
    (r'^deletepartner3/(?P<id>\d+)/$', 'deletepartner3'),
    (r'^deletepartner/(?P<id>\d+)/$', 'deletepartner'),
    (r'^results/(?P<id>\d+)/$', 'results'),
    (r'^addpracticeround/((?P<id>\d+)/)?$', 'addpracticeround'),
    (r'^manageentries/(?P<trn>\d+)/$', 'manageentries'),
    (r'^managescores/(?P<trn>\d+)/$', 'managescores'),
    (r'^managerscores/(?P<rnd>\d+)/$', 'managerscores'),
    (r'^managetrophies/(?P<trn>\d+)/$', 'managetrophies'),
    (r'^managemultitrophies/(?P<trn>\d+)/$', 'managemultitrophies'),
    (r'^managerounds/(?P<trn>\d+)/$', 'managerounds'),
    (r'^generaterounds/(?P<trn>\d+)/$', 'generaterounds'),
    (r'^managepartnershiptrophies/(?P<trn>\d+)/$', 'managepartnershiptrophies'),
    (r'^managepartnership3trophies/(?P<trn>\d+)/$', 'managepartnership3trophies'),
    (r'^manageteamtrophy/(?P<tournid>\d+)/$', 'manageteamtrophy'),
    (r'^manageteams/(?P<tournid>\d+)/$', 'manageteams'),
    (r'^managepartners3/(?P<trn>\d+)/$', 'managepartners3'),
    (r'^managepartners/(?P<trn>\d+)/$', 'managepartners'),
    (r'^deletematchentry/(?P<id>\d+)/$', 'deletematchentry'),
    (r'^addmatchentry/(?P<tourn>\d+)/((?P<id>\d+)/)?$', 'addmatchentry'),
    (r'^addpartner/(?P<tourn>\d+)/((?P<id>\d+)/)?$', 'addpartner'),
    (r'^addpartner3/(?P<tourn>\d+)/((?P<id>\d+)/)?$', 'addpartner3'),
    (r'^addteamtrophy/(?P<tournid>\d+)/((?P<id>\d+)/)?$', 'addteamtrophy'),
    (r'^addteam/(?P<tournid>\d+)/((?P<id>\d+)/)?$', 'addteam'),
    (r'^addtrophy/(?P<trn>\d+)/((?P<id>\d+)/)?$', 'addtrophy'),
    (r'^addpartnershiptrophy/(?P<trn>\d+)/((?P<id>\d+)/)?$', 'addpartnershiptrophy'),
    (r'^addpartnership3trophy/(?P<trn>\d+)/((?P<id>\d+)/)?$', 'addpartnership3trophy'),
    (r'^showcourse/(?P<id>\d+)/$', 'showcourse'),
    (r'^showresults/(?P<trp>\d+)/$', 'showresults'),
    (r'^showmultiresults/(?P<trp>\d+)/$', 'showmultiresults'),
    (r'^showpartnerresults/(?P<trp>\d+)/$', 'showpartnerresults'),
    (r'^showteamresults/(?P<trp>\d+)/$', 'showteamresults'),
    (r'^showpartner3results/(?P<trp>\d+)/$', 'showpartner3results'),
    (r'^showtee/(?P<course>\d+)/(?P<id>\d+)/$', 'showtee'),
    (r'^showscores/(?P<matchentry>\d+)/$', 'showscores'),
    (r'^scoringrecord/(?P<ply>\d+)/$', 'scoringrecord'),
    (r'^statsdisp/(?P<ply>\d+)/$', 'statsdisp'),
    (r'^showcards/(?P<mem>\d+)/$', 'showcards'),
    (r'^calindhand/$', 'calindhandicap'),
    (r'^getdups/$', 'getdups'),
    (r'^displayplayerhandicap/(?P<id>\d+)/$','displayplayerhandicap'),
)

web/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.db.models import Avg, Max, Min, Count
from django.core.exceptions import ValidationError

import datetime

def initscoredict(player):
    """returns a dict of the players scores"""
    scd = {}
    scd['player'] = player
    scd['scores'] = {}
    scd['front'] = 0
    scd['back'] = 0
    scd['total'] = 0
    return scd


def getnines(scd):
    for hl, sc in scd['scores'].items():
        if hl <= 9:
            scd['front'] += sc['sc']
        else:
            scd['back'] += sc['sc']
    scd['total'] = scd['front'] + scd['back']
    return scd


def getcolour(score, par):
    """par green, bogey white, birdie blue, eagle yellow, double grey, 3 and more red"""
    if score == 0:
        return "#f34639"
    df = score - par
    if df == -2:
        clr = "#08d0f4"
    elif df == -1:
        clr = "#0fbff9"
    elif df == 0:
        clr = "#08f47c"
    elif df == 1:
        clr = "#fbba0a"
    elif df == 2:
        clr = "#f84d0a"
    elif df < -2 and score != 0:
        clr = "white"
    else:
        clr = "red"
    return clr


def getstrokes(hcp, score):
    """given a score and handicap gets strokes"""
    if score.score == 0:
        strokes = 0
        return strokes
    if hcp >= score.hole.strokeindex + 18:
        strokes = 2
    elif hcp >= score.hole.strokeindex:
        strokes = 1
    elif hcp <= score.hole.strokeindex - 19:
        strokes = -1
        #negative handicap so strokes minus
    else:
        strokes = 0
    return strokes

# Create your models here.



class Tempreg(models.Model):
    username = models.CharField(_("User Name"), max_length=30, unique=True)
    email = models.EmailField(_("Email Address"), unique=True)
    date = models.DateField(_("Date"), default=datetime.datetime.now, editable=False)
    code = models.CharField(_("Code"), max_length=100, blank=True, null=True,
        editable=False, default='123')

    def __unicode__(self):
        return _(u"%(username)s %(email)s")\
        % {'username': self.username, 'email': self.email}

TEECOLOURS = (
    ('RD', _('Red')),
    ('BL', _('Black')),
    ('WT', _('White')),
    ('BU', _('Blue')),
    ('YL', _('Yellow')),
    )

PARTNERTYPES = (
    ('GR', _('Gross bestball bogey')),
    ('NT', _('Nett bestball bogey')),
    ('MR', _('Gross bestball medal round')),
    ('MT', _('Nett bestball medal round')),
    ('SC', _('Nett scramble')),
    ('SG', _('Gross scramble')),
    ('CS', _('Combined stableford')),
    ('GC', _('Gross combined stableford')),
    ('NS', _('Nett Switch')),
    ('GS', _('Gross Switch')),
    ('NM', _('Nett Multiply')),
    ('GM', _('Gross Multiply')),
    ('SX', _('Nett scramble stableford - 50\%')),
    ('SY', _('Nett scramble stableford - 40\%')),
    ('SZ', _('Nett scramble stableford - 30\%')),
    )

PARTNER3TYPES = (
    ('G3', _('Gross')),
    ('N3', _('Nett')),

    )
TEAMTYPES = (
    ('GG', _('GKD Gross')),
    ('GN', _('GKD Nett')),
    ('CG', _('Combined stableford Gross')),
    ('CN', _('Combined stableford Nett')),
    ('MG', _('Combined medal round Gross')),
    ('MN', _('Combined medal round Nett')),

    )
JUNIORCATS = (
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D'),
    ('E', 'A&B girls'),
    ('F', 'C girls'),

    )

MATCHTYPES = (
    ('MR', 'Medal Round'),
    ('GM', 'Gross Medal Round'),
    ('ST', 'Stableford'),
    ('AD', 'Addleford'),
    ('AG', 'Against Bogey'),
    ('GS', 'Gross Stableford'),
    ('GG', 'Gross Bogey'),
    ('MB', 'Modified Bogey'),
    ('GB', 'Gross Modified Bogey'),
    ('VL', 'Dr Velappan'),
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D'),
    ('AB', 'A & B'),
    ('BG', 'A & B girls'),
    ('CG', 'C girls'),
    )

HANDICAPTYPES = (
    ('L', 'Local handicap'),
    ('M', 'Modified by the Committee'),
    ('N', 'Nine hole'),
    ('NL', 'Nine hole local'),
    ('R', 'Automatically reduced'),
    ('SL', 'Short Course'),
    ('WD', 'Withdrawn'),
    )

SCORETYPES = (
    ('N', 'Normal'),
    ('A', 'Away'),
    ('AI', 'Away Internet'),
    ('P', 'Penalty'),
    ('T', 'Tournament'),
    ('TI', 'Tournament Internet'),
    ('C', 'Combined nines'),
    )
TOURNAMENT_KINDS = (
    ('IN', 'Individual'),
    ('PT', 'Partnership'),
    ('TM', 'Team'),
    ('P3', '3 ball Partnership'),
    )


class Course(models.Model):
    """
        Basic data for a course
        """
    name = models.CharField(_("Course name"), max_length=100, unique=True)
    shortname = models.CharField(_("Short name"), max_length=100)
    description = models.TextField(_("Description"), blank=True, null=True)
    usga = models.BooleanField(_("usga handicap index"), default=False)

    def __unicode__(self):
        return u"%s: %s" % (self.shortname, self.name)


class Homeclub(models.Model):
    """This model is designed to have softcoded details that are now hardcoded"""
    course = models.OneToOneField(Course, verbose_name=_("Course"))

    def __unicode__(self):
        return u"%s" % self.course.shortname


class Tee(models.Model):
    """various tee types - championship, ladies, gents etc
        """
    course = models.ForeignKey(Course, verbose_name=_("Course"))
    colour = models.CharField(_("Tee colour"), max_length=2, choices=TEECOLOURS)
    description = models.CharField(_("Description"), max_length=100)
    sloperating = models.IntegerField(_("Slope Rating"))
    courserating = models.DecimalField(max_digits=4, decimal_places=1,
        verbose_name=_("Course Rating"))

    def get_yardage(self):
        yards = 0
        holes = self.hole_set.all()
        for hl in holes:
            yards = yards + hl.yardage
        return yards

    def get_par(self):
        par = 0
        holes = self.hole_set.all()
        for hl in holes:
            par = par + hl.par
        return par

    def get_holes(self):
        par = 0
        holes = self.hole_set.all()
        return len(holes)

    class Meta:
        unique_together = ("course", "colour")
        ordering = ['id']

    def __unicode__(self):
        return u"%s: %s" % (self.course.shortname, self.get_colour_display())


class Hole(models.Model):
    """hole, tee colour, yardage, par and stroke index"""
    tee = models.ForeignKey(Tee, verbose_name=_("Tee"))
    number = models.IntegerField(_("Hole Number"))
    par = models.IntegerField(_("Par"))
    strokeindex = models.IntegerField(_("Stroke Index"))
    yardage = models.IntegerField(_("Yardage"))

    class Meta:
        unique_together = ("tee", "number")
        ordering = ['number']
        #need to validate that stroke index is not duplicated
        #def clean(self):
        #for hle in self.tee.hole_set.all():
        #if hle.strokeindex == self.strokeindex and hle != self:
        #raise ValidationError(_("Duplicate stroke index same as %s") %hle.number)

    def __unicode__(self):
        return u"%s: par=%d, strokeindex=%d" % (self.tee, self.par, self.strokeindex)


class Tournament(models.Model):
    """Date, name, format, days, handicap"""
    startdate = models.DateField(_("Start Date"), unique=True)
    rounds = models.IntegerField(_("Number of rounds"))
    course = models.ForeignKey(Course, verbose_name=_("Course"))
    closed = models.BooleanField(_("Results Declared"), default=False)
    kind = models.CharField(_("Type of tournament"), max_length=2, choices=TOURNAMENT_KINDS)


    def getfile(self):
        return "tournament%s" % (str(self.startdate))

    def ispartner(self):
        return self.partnershiptrophy_set.all().count() > 0

    def isteam(self):
        return self.teamtrophy_set.all().count() > 0

    def hasrounds(self):
        for rnd in self.round_set.all():
            if rnd.num > 1:
                return True
        return False

    def __unicode__(self):
        return u"%s %s" % (self.course, self.startdate)


class Round(models.Model):
    """Date, name, format, days, handicap"""
    startdate = models.DateField(_("Start Date"))
    tournament = models.ForeignKey(Tournament, verbose_name="Tournament")
    num = models.IntegerField("Round number")

    class Meta:
        unique_together = ("tournament", "num")
        ordering = ['num']

    def __unicode__(self):
        return u"%s %s %s" % (self.num, self.startdate, self.tournament)


class Trophy(models.Model):
    """Date, name, format, days, handicap"""
    tournament = models.ForeignKey(Tournament, verbose_name=_("Tournament"))
    name = models.CharField(_("Trophy Name"), max_length=100)
    format = models.CharField(_("Format"), max_length=2, choices=MATCHTYPES)
    handicapmax = models.IntegerField(_("Handicap max"))
    handicapmin = models.IntegerField(_("Handicap min"))

    def getfile(self):
        return "trophy%s%s" % (str(self.tournament.startdate), str(self.name))

    class Meta:
        unique_together = ("name", "tournament")

    def multisort(self, x, y):
        return x[1]['grandtotal'] - y[1]['grandtotal']

    def getmultiround(self):
        """this is supposed to get the results of a multiround tournament
            only medal round for now"""
        #get the players and put them in an dictionary
        lastround = 1
        entries = self.tournament.matchentry_set.all()
        scd = {}
        for ent in entries:
            if ent.round == 1:
                scd[ent.player] = {}
                #now get the  round results
        for ent in entries:
            if ent.player in scd.keys():
                if self.format == 'GM':
                    mr = ent.getgrossmr()
                if self.format == 'MR':
                    if self.handicapmax >= ent.getcoursehandicap() >= self.handicapmin:
                        mr = ent.getnettmr()
                    else:
                        mr = ['DQ']
                if mr != ['DQ']:
                    if mr['scores'] != {}:
                        if ent.round > lastround:
                            lastround = ent.round

templates/web/adddraw.html
{% extends "base.html" %}
{% load i18n %}
{% block head %}

</script>
{% endblock %}
{% block centercontent %}
    <h2 > { % if edit %}
    {%
        trans
        "Edit" %
    }
    {% else %
    }
    {%
        trans
        "Add a " %}
    {%
        endif %}
    {
        {
            title
        }
    }</h2>

    <form; enctype="multipart/form-data" method="POST" action=".">{% csrf_token %}
        {% if form.non_field_errors %}
            {{form.non_field_errors}}
        {% endif %}
            <table>
                {% for field in form %}
                    <dt>{{ field.label_tag }}</dt>
                    <dd>{{ field }}</dd>
                    {% if field.errors %} {{ field.errors }} {% endif %}
                {% endfor %}
            </table>
            <input type="submit" name="save" value="Allot teeoffs" />
            <input type="submit" name="cancel" value="Cancel" />
        </form>
{% endblock %}

templates/web/addhandicap.html
{% extends "base.html" %}
{% load i18n %}
{% block head %}
<link type="text/css" href="/sitemedia/css/themes/base/jquery.ui.all.css" rel="stylesheet" />
  <script type="text/javascript" src="/sitemedia/js/jquery.js"></script>
  <script type="text/javascript" src="/sitemedia/js/ui/jquery.ui.core.js"></script>
  <script type="text/javascript" src="/sitemedia/js/ui/jquery.ui.datepicker.js"></script>

<script type="text/javascript">
  $(document).ready(function(){
    $("#id_valfrom").datepicker({ dateFormat: 'yy-mm-dd',appendText: "Format yyyy-mm-dd" });
    $("#id_valto").datepicker({ dateFormat: 'yy-mm-dd',appendText: "Format yyyy-mm-dd" });
  });
</script>

{% endblock %}
{% block centercontent %}

    <h2>{% if edit %}
        {% trans "Edit" %}
        {% else %}
        {% trans "Add a new" %}
        {% endif %}
         {{ title }} for {{player}}</h2>
    <p>{% trans "Latest handicap is:" %} {{ player.latesthandicap }}</p>

    <form enctype="multipart/form-data" method="POST" action=".">{% csrf_token %}
        <table>
        {% if form.non_field_errors %}
        {{form.non_field_errors}}
        {% endif %}
            {% for field in form %}
    <dt>{{ field.label_tag }}</dt>
    <dd>{{ field }}</dd>
    {% if field.errors %} {{ field.errors }} {% endif %}
    {% endfor %}
        </table>
        <input type="submit" name="save" value="{% trans "Save" %}" />

        <input type="submit" name="delete" value="{% trans "Delete" %}" />
        <input type="submit" name="cancel" value="{% trans "Cancel" %}" />
  
    </form>
{% endblock %}

templates/web/additem.html
{% extends "base.html" %}
{% load i18n %}
{% block head %}
<link type="text/css" href="/sitemedia/css/themes/base/jquery.ui.all.css" rel="stylesheet" />
  <script type="text/javascript" src="/sitemedia/js/jquery.js"></script>
  <script type="text/javascript" src="/sitemedia/js/ui/jquery.ui.core.js"></script>
  <script type="text/javascript" src="/sitemedia/js/ui/jquery.ui.datepicker.js"></script>
<script type="text/javascript">
  $(document).ready(function(){
    $("#id_startdate").datepicker({ dateFormat: 'yy-mm-dd',appendText: "Format yyyy-mm-dd" });
  });
  $(document).ready(function(){
    $("#id_rounddate").datepicker({ dateFormat: 'yy-mm-dd',appendText: "Format yyyy-mm-dd" });
  });
</script>
{% endblock %}
{% block centercontent %}
    <h2>{% if edit %}
        {% trans "Edit" %}
        {% else %}
        {% trans "Add a new" %}
        {% endif %}
         {{ title }}</h2>
    {% if form.non_field_errors %}
        {{form.non_field_errors}}
        {% endif %}
    <form enctype="multipart/form-data" method="POST" action=".">{% csrf_token %}
        <table>
            {% for field in form %}
    <dt>{{ field.label_tag }}</dt>
    <dd>{{ field }}</dd>
    {% if field.errors %} {{ field.errors }} {% endif %}
    {% endfor %}
        </table>
        <input type="submit" name="save" value="{% trans "Save" %}" />
        {% if not edit %}
        <input type="submit" name="repeat" value="{% trans "Save and add another" %}" />
        {% endif %}
        <input type="submit" name="cancel" value="{% trans "Cancel" %}" />
    </form>
{% endblock %}

templates/web/addpscores.html
{% extends "base.html" %}
{% load i18n %}
{% block centercontent %}
    <h2>Add scores for {{ mentry.member }}</h2>

    <form enctype="multipart/form-data" method="POST" action=".">{% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" name="save" value="{% trans "Save" %}" />
        {% if not edit %}
        <input type="submit" name="repeat" value="{% trans "Save and add another" %}" />
        {% endif %}
        <input type="submit" name="cancel" value="{% trans "Cancel" %}" />
    </form>
{% endblock %}

templates/web/adduser.html
{% extends "base.html" %}
{% load i18n %}
{% block centercontent %}
    <h2>{% trans "Complete registration" %}</h2>
    <form method="POST" action=".">{% csrf_token %}
    <table>
        {{ form }}
        </table>
        <input type="submit" name="Register" class ="sub" value='{% trans "Submit" %}'> </p>
    </form>
{% endblock %}

templates/web/finaldraw.html
<html>
<head>
<title>Ootacamund Gymkhana club</title>
</head>
<body>
<h2>{{ startdate|date:"D d M Y" }}</h2>
{% autoescape off %}
<h3>{{ troph }}</h3>
{% endautoescape %}
{% for x in display %}
    {% if 'Tee' in x or 'Time' in x%}
        <h2>{{x}}</h2>
    {% else %}
        <p>{{x}}</p>
    {% endif %}
{% endfor %}
</body>

</html>

templates/web/leaderboard.html
{% extends "base.html" %}
{% load i18n %}
{% block head %}

<meta http-equiv="REFRESH" content="60;">
{% endblock %}
{% block centercontent %}
<p><a href = "/matchplay/{{tourn.id}}/">{% trans "Match play" %}</a></p>
<table>
    <tr>
    {% for res in results %}
        <td> <h3>{{res.0.name}} {{res.0.get_format_display}} {{res.0.handicapmin}} to {{res.0.handicapmax}}</h3>
    <table border="1">
    <tr>
        <th>Player</th>
        <th>Score</th>
    </tr>
    {% for player in res.1 %}
    
       <TR>
       <TD>{{ player.0 }}</TD>
       <td>{{player.1.total}}</td>
       </TR>
    {% endfor %}
    </table></td>
    {% endfor %}
    </tr>
</table>




{% endblock %}

templates/web/manageentries.html
{% extends "base.html" %}
{% load i18n %}
{% block centercontent %}
    <h2 >{% trans "Manage entries for" %} {{tourn}}</h2>
    <p ><a class="links" href="/addmatchentry/{{tourn.id}}/">Add a new entry</a></p>
    {% if tourn  %}
        <p >Click an entry to delete</p>
    <table>
        <TR><Th>Player</Th>
        <Th>Tee</Th>
        <Th>Handicap</Th>
        <Th>Course handicap</Th>
        <Th>Category</Th>
        </TR>
        {% for p in entries %}
           <TR><TD><a href="/deletematchentry/{{ p.id }}/">{{ p.player }}</a></TD>
           <td>{{ p.tee }}</a></td>
           <td>{{ p.getcurrenthandicap }}</a></td>
           <td>{{ p.getcoursehandicap }}</a></td>
           <td>{{ p.get_category_display }}</a></td>
           </TR>
        {% endfor %}
    </table>
    {% else %}
        <h3>{% trans "You have no tournaments entered" %}</h3><br>
    {% endif %}
{% endblock %}

templates/web/managepartnership3trophies.html
{% extends "base.html" %}
{% load i18n %}
{% block centercontent %}
    <h2 >{% trans "Manage trophies for" %} {{tourn}}</h2>

    {% if tourn  %}
    <p><a href = "/addpartnership3trophy/{{tourn.id}}/">Add a new trophy</a></p>
        <p >Click on a trophy to edit</p>
    <table border="1">
    <tr>
        <th>Trophy</th>
        <th>Handicap</th>
        <th>Format</th>
        <th>Action</th>
        <th>Action</th>
    </tr>
    {% for p in cr %}
    <tr>
        <td><a href= "/addpartnership3trophy/{{tourn.id}}/{{p.id}}/">{{p.name}}</a></td>
        <td>{{p.handicapmin}} to {{p.handicapmax}}</td>
        <td>{{p.get_format_display}}</td>
        <td><a href="/managepartners3/{{tourn.id}}/">Manage teams</a></td>
        <td><a href="/showpartner3results/{{p.id}}/">Show result</a></td>

    </tr>
    {% endfor %}
    </table>
    {% else %}
        <h3>{% trans "You have no tournaments entered" %}</h3><br>
    {% endif %}
{% endblock %}

templates/web/tournamentfull.html
{% extends "base.html" %}
{% load i18n %}
{% block centercontent %}
<h2> Tournament closed </h2>
{% endblock %}